# -*- coding: utf-8 -*-
"""Weather Trend Forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KAsKtup5fGbGUnv-W3Bse1NOEDyRFF27

# Imports
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# Importing Dataset"""

# Import from file
df = pd.read_csv('/content/GlobalWeatherRepository.csv')

"""## Exploring Dataset"""

df.head()

df.info()

df.isnull().sum()

pd.set_option('display.max_columns', None)
df.describe()

"""# Basic Assessment

## Data Cleaning, Preprocessing & EDA
"""

# Redundant Stuff
to_remove = [
    'temperature_fahrenheit', 'wind_mph', 'pressure_in',
    'precip_in', 'feels_like_fahrenheit', 'visibility_miles', 'gust_mph'
]
df_clean = df.drop(columns=to_remove)

# Remove lines with too high values for some columns
df_clean = df_clean[
    (df_clean['temperature_celsius'] < 60) & (df_clean['temperature_celsius'] > -90) &
    (df_clean['wind_kph'] < 400) &
    (df_clean['pressure_mb'] < 1100) & (df_clean['pressure_mb'] > 850)
]

# Remove rows with impossible negative air quality values
df_clean = df_clean[
    (df_clean['air_quality_Carbon_Monoxide'] >= 0) &
    (df_clean['air_quality_Sulphur_dioxide'] >= 0) &
    (df_clean['air_quality_PM10'] >= 0)
]

print(f"Lines Before: {len(df)}")
print(f"Lines After: {len(df_clean)}")
print(f"Lines Removed: {len(df) - len(df_clean)}")

air_quality_columns_to_plot = [
    'air_quality_Carbon_Monoxide',
    'air_quality_Ozone',
    'air_quality_Nitrogen_dioxide',
    'air_quality_Sulphur_dioxide',
    'air_quality_PM2.5',
    'air_quality_PM10'
]

for col in air_quality_columns_to_plot:
    plt.figure(figsize=(8, 6))
    sns.boxplot(y=df_clean[col])
    plt.title(f'Boxplot of {col.replace("air_quality_", "").replace("_", " ").title()}')
    plt.ylabel(col.replace("air_quality_", "").replace("_", " ").title() + ' Value')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()

air_quality_cols = [
    'air_quality_Carbon_Monoxide',
    'air_quality_Ozone',
    'air_quality_Nitrogen_dioxide',
    'air_quality_Sulphur_dioxide',
    'air_quality_PM2.5',
    'air_quality_PM10'
]

percentile_99_limits = {}
for col in air_quality_cols:
    upper_bound = df_clean[col].quantile(0.99)
    percentile_99_limits[col] = upper_bound

print("99th Percentile Limits for Air Quality Columns:")
for col, limit in percentile_99_limits.items():
    print(f"{col}: {limit:.2f}")

# Removendo Outliers
initial_rows_before_outlier_removal = len(df_clean)

# Create a boolean mask for rows to keep
combined_condition = pd.Series([True] * len(df_clean), index=df_clean.index)
for col, limit in percentile_99_limits.items():
    combined_condition = combined_condition & (df_clean[col] <= limit)

df_clean = df_clean[combined_condition]
rows_removed_this_step = initial_rows_before_outlier_removal - len(df_clean)

df_clean[air_quality_cols].describe()

print(f"Lines Before: {len(df)}")
print(f"Lines After: {len(df_clean)}")
print(f"Lines Removed: {len(df) - len(df_clean)}")

df_clean.describe()

df_clean.head()

# Convertendo a coluna original para o formato datetime do Pandas
df_clean['last_updated'] = pd.to_datetime(df_clean['last_updated'])

df_clean['date_only'] = df_clean['last_updated'].dt.date

print("Data inicial do dataset:", df_clean['date_only'].min())
print("Data final do dataset:", df_clean['date_only'].max())

# Agrupando por data para obter as médias diárias globais de temperatura e chuva
df_tendencia = df_clean.groupby('date_only')[['temperature_celsius', 'precip_mm']].mean().reset_index()

def temp_and_precip_plot(df):
  plt.figure(figsize=(16, 6))

  # 1. Gráfico de Linha Temperatura
  plt.subplot(1, 2, 1)
  sns.lineplot(data=df, x='date_only', y='temperature_celsius', color='crimson', linewidth=2.5)
  plt.title('Global Temperature', fontsize=12, fontweight='bold')
  plt.xlabel('Date')
  plt.ylabel('Avg Temperature (°C)')
  plt.xticks(rotation=45)
  plt.grid(True, linestyle='--', alpha=0.6)

  # 2. Gráfico de Linha Precipitação
  plt.subplot(1, 2, 2)
  sns.lineplot(data=df_tendencia, x='date_only', y='precip_mm', color='royalblue', linewidth=2.5)
  plt.title('Global Precipitation', fontsize=12, fontweight='bold')
  plt.xlabel('Date')
  plt.ylabel('Avg Precipitation (mm)')
  plt.xticks(rotation=45)
  plt.grid(True, linestyle='--', alpha=0.6)

  plt.tight_layout()
  plt.show()
temp_and_precip_plot(df_tendencia)

def corr_matrix_plot(df, columns):
  matriz_correlacao = df[columns].corr()

  # Gerando o Heatmap
  plt.figure(figsize=(12, 10))
  sns.heatmap(
      matriz_correlacao,
      annot=True,
      cmap='coolwarm',
      fmt=".2f",
      linewidths=0.5,
      vmin=-1, vmax=1
  )

  plt.title('Correlation Matrix', fontsize=14, fontweight='bold', pad=20)
  plt.tight_layout()
  plt.show()

colunas_para_estudo = [
    'temperature_celsius', 'feels_like_celsius', 'precip_mm',
    'humidity', 'cloud', 'wind_kph', 'pressure_mb', 'uv_index',
    'air_quality_Carbon_Monoxide', 'air_quality_Ozone', 'air_quality_PM2.5'
]
corr_matrix_plot(df_clean, colunas_para_estudo)

# Recalculando a média diária para achar as datas com os outliers
df_tendencia = df_clean.groupby('date_only')['temperature_celsius'].mean().reset_index()

df_tendencia['variacao_diaria'] = df_tendencia['temperature_celsius'].diff().abs()

datas_anomalas_2024 = df_tendencia[df_tendencia['variacao_diaria'] > 3]['date_only']
print("Dates with Outliers:", datas_anomalas_2024.values)

# Removendo essas datas do nosso dataset principal
df_clean = df_clean[~df_clean['date_only'].isin(datas_anomalas_2024)]

df_daily_averages = df_clean.groupby('date_only')[['temperature_celsius', 'precip_mm']].mean().reset_index()

# Update the global df_tendencia so the function finds 'precip_mm' for the second plot.
df_tendencia = df_daily_averages

temp_and_precip_plot(df_daily_averages)

corr_matrix_plot(df_clean, colunas_para_estudo)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Selecionando apenas as colunas numéricas contínuas (não queremos normalizar latitude, longitude ou datas)
colunas_para_normalizar = [
    'temperature_celsius', 'wind_kph', 'pressure_mb', 'precip_mm',
    'humidity', 'cloud', 'feels_like_celsius', 'visibility_km', 'uv_index',
    'air_quality_Carbon_Monoxide', 'air_quality_Ozone',
    'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide',
    'air_quality_PM2.5', 'air_quality_PM10'
]

# Aplicando a normalização e substituindo os valores no dataframe limpo
df_clean[colunas_para_normalizar] = scaler.fit_transform(df_clean[colunas_para_normalizar])

# Verificando como os dados ficaram após a transformação
print(df_clean[colunas_para_normalizar].head())

"""## Model Building"""

# Agrupando agora com as variáveis interessantes
colunas_interesse = ['temperature_celsius', 'humidity', 'uv_index', 'pressure_mb']
df_model = df_clean.groupby('date_only')[colunas_interesse].mean().reset_index()
df_model = df_model.sort_values('date_only')

# Features da variável principal
df_model['lag_1_temp'] = df_model['temperature_celsius'].shift(1)

# Features das variáveis extras
df_model['lag_1_humidity'] = df_model['humidity'].shift(1)
df_model['lag_1_uv'] = df_model['uv_index'].shift(1)
df_model['lag_1_pressure'] = df_model['pressure_mb'].shift(1)

# Limpando os valores nulos gerados pelos lags
df_model = df_model.dropna()

X = df_model[[
    'lag_1_temp', 'lag_1_humidity', 'lag_1_uv', 'lag_1_pressure'
]]
y = df_model['temperature_celsius']

# Train-test split
# Separando 80% dos dados mais antigos para treino, e os 20% mais recentes para teste
tamanho_treino = int(len(df_model) * 0.8)

X_train, X_test = X.iloc[:tamanho_treino], X.iloc[tamanho_treino:]
y_train, y_test = y.iloc[:tamanho_treino], y.iloc[tamanho_treino:]
datas_test = df_model['date_only'].iloc[tamanho_treino:]

print(f"Tamanho do Treino: {len(X_train)} dias")
print(f"Tamanho do Teste: {len(X_test)} dias")

# Training
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

modelo_lr = LinearRegression()
modelo_lr.fit(X_train, y_train)

# Predicting
previsoes = modelo_lr.predict(X_test)

# Metrics
mae = mean_absolute_error(y_test, previsoes)
mse = mean_squared_error(y_test, previsoes)
rmse = np.sqrt(mse)

print("--- Linear Regression Model ---")
print(f"MAE (Mean Absolute Error): {mae:.4f}")
print(f"MSE (Mean Squared Error): {mse:.4f}")
print(f"RMSE (Root Mean Squared Error): {rmse:.4f}")

# Plots and data viz
plt.figure(figsize=(14, 6))
plt.plot(datas_test, y_test.values, label='Real Values', color='royalblue', linewidth=2)

plt.plot(datas_test, previsoes, label='Model Prediction', color='darkorange', linestyle='--', linewidth=2)

plt.title('Linear Regression Model', fontsize=14, fontweight='bold')
plt.xlabel('Date')
plt.ylabel('Temperature (Normalized)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""## Model 2"""

# Agrupando agora com as variáveis interessantes
colunas_interesse = ['temperature_celsius', 'humidity', 'uv_index', 'pressure_mb']
df_model2 = df_clean.groupby('date_only')[colunas_interesse].mean().reset_index()
df_model2 = df_model2.sort_values('date_only')

# Features da variável principal
df_model2['temp_ontem'] = df_model2['temperature_celsius'].shift(1)

# Limpando os valores nulos gerados pelos lags
df_model2 = df_model2.dropna()

X = df_model2[['temp_ontem']]
y = df_model2['temperature_celsius']

# Train-test split
# Separando 80% dos dados mais antigos para treino, e os 20% mais recentes para teste
tamanho_treino = int(len(df_model2) * 0.8)

X_train, X_test = X.iloc[:tamanho_treino], X.iloc[tamanho_treino:]
y_train, y_test = y.iloc[:tamanho_treino], y.iloc[tamanho_treino:]
datas_test = df_model2['date_only'].iloc[tamanho_treino:]

print(f"Tamanho do Treino: {len(X_train)} dias")
print(f"Tamanho do Teste: {len(X_test)} dias")

# Training
modelo_lr2 = LinearRegression()
modelo_lr2.fit(X_train, y_train)

# Predicting
previsoes = modelo_lr2.predict(X_test)

# Metrics
mae = mean_absolute_error(y_test, previsoes)
mse = mean_squared_error(y_test, previsoes)
rmse = np.sqrt(mse)

print("--- Linear Regression Model ---")
print(f"MAE (Mean Absolute Error): {mae:.4f}")
print(f"MSE (Mean Squared Error): {mse:.4f}")
print(f"RMSE (Root Mean Squared Error): {rmse:.4f}")

# Plots and data viz
plt.figure(figsize=(14, 6))
plt.plot(datas_test, y_test.values, label='Real Values', color='royalblue', linewidth=2)

plt.plot(datas_test, previsoes, label='Model Prediction', color='darkorange', linestyle='--', linewidth=2)

plt.title('Linear Regression Model', fontsize=14, fontweight='bold')
plt.xlabel('Date')
plt.ylabel('Temperature (Normalized)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""## Model 3"""

# Agrupando agora com as variáveis interessantes
colunas_interesse = ['temperature_celsius', 'humidity', 'uv_index', 'pressure_mb']
df_model3 = df_clean.groupby('date_only')[colunas_interesse].mean().reset_index()
df_model3 = df_model3.sort_values('date_only')

# Features das variáveis extras
df_model3['lag_1_humidity'] = df_model3['humidity'].shift(1)
df_model3['lag_1_uv'] = df_model3['uv_index'].shift(1)
df_model3['lag_1_pressure'] = df_model3['pressure_mb'].shift(1)

# Limpando os valores nulos gerados pelos lags
df_model3 = df_model3.dropna()

X = df_model[[
    'lag_1_humidity', 'lag_1_uv', 'lag_1_pressure'
]]
y = df_model3['temperature_celsius']

# Train-test split
# Separando 80% dos dados mais antigos para treino, e os 20% mais recentes para teste
tamanho_treino = int(len(df_model2) * 0.8)

X_train, X_test = X.iloc[:tamanho_treino], X.iloc[tamanho_treino:]
y_train, y_test = y.iloc[:tamanho_treino], y.iloc[tamanho_treino:]
datas_test = df_model3['date_only'].iloc[tamanho_treino:]

print(f"Tamanho do Treino: {len(X_train)} dias")
print(f"Tamanho do Teste: {len(X_test)} dias")

# Training
modelo_lr3 = LinearRegression()
modelo_lr3.fit(X_train, y_train)

# Predicting
previsoes = modelo_lr3.predict(X_test)

# Metrics
mae = mean_absolute_error(y_test, previsoes)
mse = mean_squared_error(y_test, previsoes)
rmse = np.sqrt(mse)

print("--- Linear Regression Model ---")
print(f"MAE (Mean Absolute Error): {mae:.4f}")
print(f"MSE (Mean Squared Error): {mse:.4f}")
print(f"RMSE (Root Mean Squared Error): {rmse:.4f}")

# Plots and data viz
plt.figure(figsize=(14, 6))
plt.plot(datas_test, y_test.values, label='Real Values', color='royalblue', linewidth=2)

plt.plot(datas_test, previsoes, label='Model Prediction', color='darkorange', linestyle='--', linewidth=2)

plt.title('Linear Regression Model', fontsize=14, fontweight='bold')
plt.xlabel('Date')
plt.ylabel('Temperature (Normalized)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

